import type { Shipment, ContainerMatch, DashboardStats } from "@/types";

export const PORTS = [
  "Shanghai, China (CNSHA)",
  "Singapore (SGSIN)",
  "Rotterdam, Netherlands (NLRTM)",
  "Los Angeles, USA (USLAX)",
  "Hamburg, Germany (DEHAM)",
  "Dubai, UAE (AEJEA)",
  "Hong Kong, China (HKHKG)",
  "Busan, South Korea (KRPUS)",
  "New York, USA (USNYC)",
  "Antwerp, Belgium (BEANR)",
  "Felixstowe, UK (GBFXT)",
  "Sydney, Australia (AUSYD)",
  "Mumbai, India (INBOM)",
  "Tokyo, Japan (JPTYO)",
  "Barcelona, Spain (ESBCN)",
];

export const CARGO_TYPES = [
  "General Merchandise",
  "Electronics & Technology",
  "Furniture & Home Goods",
  "Clothing & Textiles",
  "Food & Beverages",
  "Industrial Equipment",
  "Automotive Parts",
  "Books & Paper Products",
  "Toys & Games",
  "Health & Beauty",
  "Sports Equipment",
  "Building Materials",
];

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: "shp-001",
    trackingNumber: "SC2024-0891-TL",
    origin: "Shanghai, China (CNSHA)",
    destination: "Rotterdam, Netherlands (NLRTM)",
    departureDate: "2024-12-15",
    estimatedArrival: "2025-01-18",
    cargoType: "Electronics & Technology",
    weight: 2400,
    volume: 8.5,
    status: "in_transit",
    containerShare: {
      containerType: "40ft",
      totalCapacity: 67,
      usedCapacity: 54,
      yourShare: 8.5,
      fillPercentage: 81,
    },
    pricing: {
      fullContainerCost: 4800,
      yourBaseCost: 610,
      bookingFee: 45,
      serviceFee: 72,
      managementFee: 38,
      totalCost: 765,
      savings: 4035,
      savingsPercentage: 84,
      currency: "USD",
    },
    coShippers: [
      { id: "cs-1", name: "TechFlow GmbH", verificationLevel: "premium", cargoType: "Electronics", volumeShare: 22 },
      { id: "cs-2", name: "EuroGoods BV", verificationLevel: "verified", cargoType: "General Merchandise", volumeShare: 15 },
      { id: "cs-3", name: "Nordic Trade AS", verificationLevel: "verified", cargoType: "Furniture", volumeShare: 8.5 },
    ],
    milestones: [
      { id: "m1", event: "Booking Confirmed", location: "Shanghai, CN", timestamp: "2024-12-08 09:00", completed: true, current: false },
      { id: "m2", event: "Cargo Received at Port", location: "Shanghai Port", timestamp: "2024-12-13 14:30", completed: true, current: false },
      { id: "m3", event: "Vessel Departed", location: "Shanghai, CN", timestamp: "2024-12-15 22:00", completed: true, current: false },
      { id: "m4", event: "Singapore Transshipment", location: "Singapore", timestamp: "2024-12-20 08:00", completed: true, current: true },
      { id: "m5", event: "Suez Canal Transit", location: "Suez Canal, EG", timestamp: "2025-01-02 00:00", completed: false, current: false },
      { id: "m6", event: "Arrived at Rotterdam", location: "Rotterdam, NL", timestamp: "2025-01-18 06:00", completed: false, current: false },
      { id: "m7", event: "Delivery Completed", location: "Rotterdam, NL", timestamp: "2025-01-20 00:00", completed: false, current: false },
    ],
    createdAt: "2024-12-05",
  },
  {
    id: "shp-002",
    trackingNumber: "SC2024-0734-BK",
    origin: "Los Angeles, USA (USLAX)",
    destination: "Hamburg, Germany (DEHAM)",
    departureDate: "2024-11-28",
    estimatedArrival: "2025-01-04",
    cargoType: "Clothing & Textiles",
    weight: 1800,
    volume: 12,
    status: "in_transit",
    containerShare: {
      containerType: "40ft HC",
      totalCapacity: 76,
      usedCapacity: 70,
      yourShare: 12,
      fillPercentage: 92,
    },
    pricing: {
      fullContainerCost: 5200,
      yourBaseCost: 820,
      bookingFee: 45,
      serviceFee: 98,
      managementFee: 52,
      totalCost: 1015,
      savings: 4185,
      savingsPercentage: 80,
      currency: "USD",
    },
    coShippers: [
      { id: "cs-4", name: "Pacific Brands LLC", verificationLevel: "premium", cargoType: "Apparel", volumeShare: 35 },
      { id: "cs-5", name: "West Coast Trading", verificationLevel: "verified", cargoType: "Textiles", volumeShare: 23 },
    ],
    milestones: [
      { id: "m8", event: "Booking Confirmed", location: "Los Angeles, US", timestamp: "2024-11-20 10:00", completed: true, current: false },
      { id: "m9", event: "Cargo Received at Port", location: "LA Port", timestamp: "2024-11-25 09:00", completed: true, current: false },
      { id: "m10", event: "Vessel Departed", location: "Los Angeles, US", timestamp: "2024-11-28 16:00", completed: true, current: false },
      { id: "m11", event: "Mid-Atlantic Transit", location: "Atlantic Ocean", timestamp: "2024-12-18 00:00", completed: true, current: true },
      { id: "m12", event: "Arrived at Hamburg", location: "Hamburg, DE", timestamp: "2025-01-04 08:00", completed: false, current: false },
      { id: "m13", event: "Delivery Completed", location: "Hamburg, DE", timestamp: "2025-01-06 00:00", completed: false, current: false },
    ],
    createdAt: "2024-11-18",
  },
  {
    id: "shp-003",
    trackingNumber: "SC2024-0612-SG",
    origin: "Singapore (SGSIN)",
    destination: "Sydney, Australia (AUSYD)",
    departureDate: "2024-10-10",
    estimatedArrival: "2024-10-28",
    cargoType: "Food & Beverages",
    weight: 3200,
    volume: 6.5,
    status: "delivered",
    containerShare: {
      containerType: "20ft",
      totalCapacity: 33,
      usedCapacity: 29,
      yourShare: 6.5,
      fillPercentage: 88,
    },
    pricing: {
      fullContainerCost: 2200,
      yourBaseCost: 433,
      bookingFee: 35,
      serviceFee: 52,
      managementFee: 28,
      totalCost: 548,
      savings: 1652,
      savingsPercentage: 75,
      currency: "USD",
    },
    coShippers: [
      { id: "cs-6", name: "Asia Pacific Foods", verificationLevel: "premium", cargoType: "Food Products", volumeShare: 14 },
      { id: "cs-7", name: "Oceanic Imports", verificationLevel: "verified", cargoType: "Beverages", volumeShare: 8.5 },
    ],
    milestones: [
      { id: "m14", event: "Booking Confirmed", location: "Singapore", timestamp: "2024-10-02 11:00", completed: true, current: false },
      { id: "m15", event: "Cargo Received at Port", location: "Singapore Port", timestamp: "2024-10-07 14:00", completed: true, current: false },
      { id: "m16", event: "Vessel Departed", location: "Singapore", timestamp: "2024-10-10 20:00", completed: true, current: false },
      { id: "m17", event: "Arrived at Sydney", location: "Sydney, AU", timestamp: "2024-10-28 07:00", completed: true, current: false },
      { id: "m18", event: "Delivery Completed", location: "Sydney, AU", timestamp: "2024-10-30 14:00", completed: true, current: false },
    ],
    createdAt: "2024-10-01",
  },
];

export const MOCK_MATCHES: ContainerMatch[] = [
  {
    id: "match-001",
    matchScore: 97,
    containerType: "40ft",
    availableSpace: 18.5,
    departureDate: "2025-01-22",
    originPort: "Shanghai, China (CNSHA)",
    destinationPort: "Rotterdam, Netherlands (NLRTM)",
    currentShippers: 3,
    maxShippers: 5,
    estimatedTransitDays: 32,
    shippingLine: "COSCO Shipping",
    pricing: {
      fullContainerCost: 4800,
      yourBaseCost: 720,
      bookingFee: 45,
      serviceFee: 86,
      managementFee: 46,
      totalCost: 897,
      savings: 3903,
      savingsPercentage: 81,
      currency: "USD",
    },
    coShippers: [
      { id: "cs-a", name: "EuroMart Trading", verificationLevel: "premium", cargoType: "Electronics", volumeShare: 20 },
      { id: "cs-b", name: "Rhine Logistics", verificationLevel: "verified", cargoType: "Machinery", volumeShare: 14 },
      { id: "cs-c", name: "Global Goods Co.", verificationLevel: "verified", cargoType: "Consumer Goods", volumeShare: 12 },
    ],
  },
  {
    id: "match-002",
    matchScore: 89,
    containerType: "40ft HC",
    availableSpace: 22,
    departureDate: "2025-01-18",
    originPort: "Shanghai, China (CNSHA)",
    destinationPort: "Rotterdam, Netherlands (NLRTM)",
    currentShippers: 2,
    maxShippers: 4,
    estimatedTransitDays: 30,
    shippingLine: "Maersk Line",
    pricing: {
      fullContainerCost: 5100,
      yourBaseCost: 765,
      bookingFee: 45,
      serviceFee: 92,
      managementFee: 48,
      totalCost: 950,
      savings: 4150,
      savingsPercentage: 81,
      currency: "USD",
    },
    coShippers: [
      { id: "cs-d", name: "Atlantic Trade Group", verificationLevel: "premium", cargoType: "General Goods", volumeShare: 32 },
      { id: "cs-e", name: "NL Imports BV", verificationLevel: "verified", cargoType: "Textiles", volumeShare: 22 },
    ],
  },
  {
    id: "match-003",
    matchScore: 74,
    containerType: "20ft",
    availableSpace: 8,
    departureDate: "2025-01-28",
    originPort: "Shanghai, China (CNSHA)",
    destinationPort: "Rotterdam, Netherlands (NLRTM)",
    currentShippers: 4,
    maxShippers: 6,
    estimatedTransitDays: 35,
    shippingLine: "MSC Mediterranean",
    pricing: {
      fullContainerCost: 2600,
      yourBaseCost: 315,
      bookingFee: 35,
      serviceFee: 38,
      managementFee: 20,
      totalCost: 408,
      savings: 2192,
      savingsPercentage: 84,
      currency: "USD",
    },
    coShippers: [
      { id: "cs-f", name: "SinoEuro Express", verificationLevel: "verified", cargoType: "Consumer Goods", volumeShare: 8 },
      { id: "cs-g", name: "Harbor Freight Co.", verificationLevel: "basic", cargoType: "General Goods", volumeShare: 6 },
      { id: "cs-h", name: "East West Trade", verificationLevel: "verified", cargoType: "Electronics", volumeShare: 5 },
      { id: "cs-i", name: "Pacific Links Ltd", verificationLevel: "basic", cargoType: "Textiles", volumeShare: 6 },
    ],
  },
];

export interface PaymentRecord {
  id: string;
  date: string;
  shipmentRef: string;
  route: string;
  containerType: string;
  shippingLine: string;
  transportationAmount: number;
  arrangementAmount: number;
  platformAmount: number;
  totalAmount: number;
  currency: string;
  status: "paid" | "refunded" | "pending";
}

export const MOCK_PAYMENT_HISTORY: PaymentRecord[] = [
  {
    id: "pay-001",
    date: "2024-12-08",
    shipmentRef: "SC2024-0891-TL",
    route: "Shanghai, CN → Rotterdam, NL",
    containerType: "40ft Container",
    shippingLine: "COSCO Shipping",
    transportationAmount: 580,
    arrangementAmount: 139,
    platformAmount: 46,
    totalAmount: 765,
    currency: "USD",
    status: "paid",
  },
  {
    id: "pay-002",
    date: "2024-11-20",
    shipmentRef: "SC2024-0734-BK",
    route: "Los Angeles, US → Hamburg, DE",
    containerType: "40ft HC Container",
    shippingLine: "Maersk Line",
    transportationAmount: 765,
    arrangementAmount: 155,
    platformAmount: 95,
    totalAmount: 1015,
    currency: "USD",
    status: "paid",
  },
  {
    id: "pay-003",
    date: "2024-10-02",
    shipmentRef: "SC2024-0612-SG",
    route: "Singapore → Sydney, AU",
    containerType: "20ft Container",
    shippingLine: "MSC Mediterranean",
    transportationAmount: 390,
    arrangementAmount: 95,
    platformAmount: 63,
    totalAmount: 548,
    currency: "USD",
    status: "paid",
  },
  {
    id: "pay-004",
    date: "2024-08-15",
    shipmentRef: "SC2024-0501-HK",
    route: "Hong Kong, CN → New York, US",
    containerType: "40ft Container",
    shippingLine: "ONE Ocean Network",
    transportationAmount: 840,
    arrangementAmount: 175,
    platformAmount: 88,
    totalAmount: 1103,
    currency: "USD",
    status: "paid",
  },
  {
    id: "pay-005",
    date: "2024-07-03",
    shipmentRef: "SC2024-0388-DU",
    route: "Dubai, UAE → Barcelona, ES",
    containerType: "20ft Container",
    shippingLine: "CMA CGM",
    transportationAmount: 310,
    arrangementAmount: 82,
    platformAmount: 45,
    totalAmount: 437,
    currency: "USD",
    status: "refunded",
  },
  {
    id: "pay-006",
    date: "2024-06-12",
    shipmentRef: "SC2024-0271-BU",
    route: "Busan, KR → Rotterdam, NL",
    containerType: "40ft HC Container",
    shippingLine: "HMM",
    transportationAmount: 695,
    arrangementAmount: 142,
    platformAmount: 72,
    totalAmount: 909,
    currency: "USD",
    status: "paid",
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalShipments: 12,
  activeShipments: 2,
  totalSavings: 24680,
  avgSavingsPercentage: 79,
  totalVolumeShipped: 142,
  co2Saved: 8.4,
};
